name: React App Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Remove Old Docker Image
        run: |
          docker image rm react-app:latest || true

      - name: Build Docker Image
        run: |
          docker build -t react-app:latest .

      - name: Stop Existing Container
        run: |
          docker stop react-container || true

      - name: Remove Existing Container
        run: |
          docker rm react-container || true

      - name: Run New Container
        run: |
          docker run -d \
          --name react-container \
          -p 3000:80 \
          --restart unless-stopped \
          react-app:latest

      - name: Verify Running Containers
        run: docker ps
